apiVersion: v2
name: bookstack
description: Wiki application made by Bookstack and MySQL
type: application
version: 1.1.0
appVersion: 0.29.1
sources:
  - https://github.com/pacroy/bookstack
maintainers:
  - name: Par
    email: pacroy@gmail.com